# Generated by Django 5.0.1 on 2024-01-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_value', models.IntegerField()),
                ('delivery_distance', models.IntegerField()),
                ('number_of_items', models.IntegerField()),
                ('time', models.CharField(max_length=255)),
            ],
        ),
    ]
