# Generated by Django 5.0.1 on 2024-01-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_value',
            field=models.IntegerField(null=True),
        ),
    ]
