# Generated by Django 5.0.1 on 2024-01-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryfeeapi', '0002_alter_order_cart_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_distance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='number_of_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
